name:                infernal
version:             0.1.0
github:              "ejconlon/infernal"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/infernal#readme>

dependencies:
- base >= 4.12 && < 5
- aeson >=1.4
- binary >= 0.8
- bytestring >=0.10
- case-insensitive >=1.2
- containers >=0.6
- heart-core >=0.1
- heart-app >=0.1
- http-client >=0.6
- http-types >=0.12
- mtl >=2.2
- text >=1.2
- unordered-containers >=0.2
- wai >=3.2

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - Rank2Types
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  infernal-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - infernal
    - tasty
    - tasty-discover
    - tasty-hunit
