AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: infernal-simple-demo

Resources:
  InfernalDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../.build/function.zip
      Handler: not-used
      Runtime: provided
