AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: infernal-demo

Resources:
  InfernalSimpleDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../.build/simple-function.zip
      Handler: not-used
      Runtime: provided

  InfernalWaiDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../.build/wai-function.zip
      Handler: not-used
      Runtime: provided
