name:                infernal
version:             0.1.0
github:              "ejconlon/infernal"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"

description: Please see the README on GitHub at <https://github.com/ejconlon/infernal#readme>

dependencies:
- base >= 4.12 && < 5
- aeson >=1.4
- binary >= 0.8
- bytestring >=0.10
- case-insensitive >=1.2
- containers >=0.6
- exceptions >=0.10
- heart-app >=0.1.1
- http-client >=0.6
- http-types >=0.12
- mtl >=2.2
- text >=1.2
- unliftio >=0.2
- unordered-containers >=0.2
- wai >=3.2

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - GADTs
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings
  - TemplateHaskell
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
