name:                infernal-demo
version:             0.1.0
github:              "ejconlon/infernal"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"

description: Please see the README on GitHub at <https://github.com/ejconlon/infernal#readme>

dependencies:
- base >= 4.12 && < 5

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings
  - TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

executables:
  infernal-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - infernal
    - aeson >=1.4
    - heart-app >=0.1.1
    - text >=1.2
