name:                infernal-demo
version:             0.6.0
github:              "ejconlon/infernal"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"

description: Please see the README on GitHub at <https://github.com/ejconlon/infernal#readme>

dependencies:
- base >= 4.12 && <5

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

executables:
  infernal-simple-demo:
    main:                Main.hs
    source-dirs:         simple-app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - infernal
    - aeson >= 2.0 && < 2.1
    - exceptions >= 0.10 && < 0.11
    - text >= 1.2 && < 1.3
    - little-logger >= 1.0.1 && < 1.1

  infernal-wai-demo:
    main:                Main.hs
    source-dirs:         wai-app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - infernal
    - scotty >= 0.12 && < 0.13
