AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-demo

Resources:
  InfernalDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../infernal-demo/.build/function.zip
      Handler: my-handler
      Runtime: provided
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
